#ifndef PTL_UUID_H
#define PTL_UUID_H
#include <linux/types.h>
/**
 * UUID encoding overview
 *
 * The ptl_uuid is a packed 64‑bit value that carries both Portals4
 * match_bits and connection metadata (QP numbers and CQ id).
 *
 * Bit layout (bit 0 = least significant bit):
 *
 *   [63.............................................0]
 *    63        48 47        32 31        16 15       0
 *   +------------+------------+------------+----------+
 *   | match_bits |   CQ id    | initiator  |  target  |
 *   |  (P4 MB)   | (bits 32–47)| QP num   | QP num   |
 *   | (bits 48–63)|          | (bits 16–31)| (0–15)  |
 *   +------------+------------+------------+----------+
 *
 * Fields:
 *   - Target QP number     (bits 0–15)
 *       Stored in the least significant 16 bits of the UUID.
 *       Accessed via:
 *         - ptl_uuid_set_target_qp_num()
 *         - ptl_uuid_get_target_qp_num()
 *
 *   - Initiator QP number  (bits 16–31)
 *       Stored in the next 16 bits above the target QP.
 *       Accessed via:
 *         - ptl_uuid_set_initiator_qp_num()
 *         - ptl_uuid_get_initiator_qp_num()
 *
 *   - Completion queue id  (bits 32–47)
 *       Stored in the next 16 bits above the initiator QP.
 *       Accessed via:
 *         - ptl_uuid_set_cq_num()
 *         - ptl_uuid_get_cq_num()
 *
 *   - Portals4 match bits  (bits 48–63)
 *       The most significant 16 bits are reserved for Portals4
 *       match_bits. These are generated by:
 *         - ptl_uuid_get_next_match_bit()
 *
 * Portals4 ignore mask semantics:
 *
 *   PTL_UUID_IGNORE_MASK (0x0000FFFFUL)
 *
 *   This constant is used as the Portals4 ignore_bits mask. By
 *   Portals4 convention:
 *     - bit = 0  → this bit must match exactly
 *     - bit = 1  → "don't care" / ignored in the match
 *
 *   With PTL_UUID_IGNORE_MASK = 0x0000FFFFUL:
 *     - Lower 16 bits  (0–15)  are marked "don't care" (ignored by match)
 *       and are used for the target QP number.
 *     - Upper 48 bits  (16–63) must match exactly and contain:
 *         * initiator QP
 *         * CQ id
 *         * match_bits (top 16 bits)
 *
 *   The helper:
 *     - ptl_uuid_set_match_list()
 *
 *   updates only the match‑relevant bits (upper 48 bits) while
 *   preserving the low 16 bits (target QP) that are ignored by
 *   the Portals4 matching logic.
 */
/* In a nutshell 1 is reserved for target srq and 2 for RMA operations to the initiator*/
#define PTL_UUID_TARGET_SRQ_MATCH_BITS 0x0001000000000000UL
#define PTL_UUID_RMA_MASK              0x0002000000000000UL
#define PTL_UUID_TARGET_COMPLETION_QUEUE_ID  0

#define PTL_UUID_SEND_RECV_MASK 0x4000000000000000UL

/* *
 * We use the 2 most significant bytes for match bits. Remember:
 * 0 --> I need to match this bit
 * F --> I do not care.
 * */
#define PTL_UUID_IGNORE_MASK          0x0000FFFFFFFFFFFFUL

u64 ptl_uuid_get_next_match_bit(void);

u64 ptl_uuid_set_match_list(u64 uuid, u64 match_list);


u64 ptl_uuid_set_target_qp_num(u64 uuid, int qp_num);

int ptl_uuid_get_target_qp_num(u64 uuid);

u64 ptl_uuid_set_initiator_qp_num(u64 uuid, int qp_num);

int ptl_uuid_get_initiator_qp_num(u64 uuid);

int ptl_uuid_get_cq_num(u64 uuid);

u64 ptl_uuid_set_cq_num(u64 uuid, int cq_num);
#endif

